### ISSUE TITLE
igv-webapp issue in building project

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv-webapp#154]
Hi
in the `igv-webapp/ `directory I run
`$ npm install
`and I get the following [output]( https://pastebin.com/jtfB0EaN)
then I build the prj
`$ npm run build
`
and I get the following
```
error: > igv-webapp@1.1.0 build /home/martina/PycharmProjects/igv_cst_prj/igv-webapp
> node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js
js/app.js → dist/app_bundle.js, dist/app_bundle.min.js...
[!] Error: Could not resolve '../node_modules/igv-widgets/dist/igv-widgets.js' from js/app.js
Error: Could not resolve '../node_modules/igv-widgets/dist/igv-widgets.js' from js/app.js
    at error (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:38:28)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! igv-webapp@1.1.0 build: `node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the igv-webapp@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martina/.npm/_logs/2020-07-21T10_15_48_769Z-debug.log

```
I've looked for `node_modules/igv-widgets/dist/igv-widgets.js` but indeed there is not the `dist` dir in that location.
The issue involves only the` igv-widgets` widget.
Last week I built with success the webapp, with zero issues. 
What can possibly be the source of the error?

**Comment by turner** [comment]
I cannot reproduce this error. Have you pulled the latest version from master?

**Comment by turner** [comment]
Actually we have reproduced the error and are looking at it now.

**Comment by turner** [comment]
Turns out it didn't work on a system that was running npm 6.13.4, but when we installed the latest version of npm (6.14.6) the build worked just fine. Can you try that?

**Comment by jrobinso** [comment]
@martina-g Apologies for the build problems.    We are working on understanding the source of this dependency tracing breakdown and will roll out something more robust soon.   In the meantime using the latest NPM seems to help.

**Comment by martina-g** [comment]
Thank you for the fast reply.

I upgraded npm:
`$sudo npm install npm -g
`
Now my npm version is 6.14.7.
When I build the app the source of the breakdown changes:

 ```
igv-webapp@1.1.0 build /home/martina/PycharmProjects/igv_cst_prj/igv-webapp
> node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js

js/app.js → dist/app_bundle.js, dist/app_bundle.min.js...
[!] Error: Could not resolve '../node_modules/igv-ui/src/index.js' from js/app.js
Error: Could not resolve '../node_modules/igv-ui/src/index.js' from js/app.js
    at error (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/martina/PycharmProjects/igv_cst_prj/igv-webapp/node_modules/rollup/dist/shared/node-entry.js:38:28)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! igv-webapp@1.1.0 build: `node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the igv-webapp@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martina/.npm/_logs/2020-07-22T09_03_30_490Z-debug.log
```
hopefully this new error can help you to find the "bug".

**Comment by jrobinso** [comment]
Did you try a fresh pull from master?   If not please do.

**Comment by martina-g** [comment]
I cloned the project from scratch and the build works.
I did not pull because I need time to check the conflicts. If there is no other way to fix this, I rather prefer adding my code to the newly cloned repo.
