### ISSUE TITLE
Incompatible module with yarn install

### ISSUE THREAD

**Issue by antonylebechec** [igvteam/igv-webapp#235]
Dear IGV team,

I have this error when I use the command "yarn install":
```
error @rollup/plugin-babel@5.3.0: The engine "node" is incompatible with this module. Expected version ">= 10.0.0". Got "8.10.0"
verbose 2.651 Error: Found incompatible module.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at checkOne (/usr/local/lib/node_modules/yarn/lib/cli.js:48237:11)
    at Object.check (/usr/local/lib/node_modules/yarn/lib/cli.js:48256:5)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:7348:73
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at <anonymous>
error Found incompatible module.
```

I use Docker with this Dockerfile:

```
FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
ADD https://raw.githubusercontent.com/dceoy/print-github-tags/master/print-github-tags /usr/local/bin/print-github-tags
RUN set -e \
      && ln -sf bash /bin/sh
RUN set -e \
      && apt-get -y update \
      && apt-get -y dist-upgrade \
      && apt-get -y install --no-install-recommends --no-install-suggests \
        ca-certificates curl git npm \
      && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
RUN set -e \
      && npm install -g npm
RUN set -eo pipefail \
      && chmod +x /usr/local/bin/print-github-tags \
      && print-github-tags --latest --tar igvteam/igv-webapp \
        | xargs -i curl -SL {} -o /tmp/igv-webapp.tar.gz \
      && tar xvf /tmp/igv-webapp.tar.gz -C /usr/local/src --remove-files \
      && mv /usr/local/src/igv-webapp-* /usr/local/src/igv-webapp \
      && cd /usr/local/src/igv-webapp \
      && sed -ie 's/http-server -a localhost dist/http-server -a 0.0.0.0 dist/' package.json \
      && rm package.jsone \
      && npm install \
      && npm run build
EXPOSE 8080
ENTRYPOINT ["npm", "start", "--prefix=/usr/local/src/igv-webapp"]
```

Do you have any explanation and solution?

Thanks a lot!

**Comment by antonylebechec** [comment]
Bug found and fixed!
It was due to ubuntu release.
I forced ubuntu 20.04:
```
FROM ubuntu:20.04
```

**Comment by jrobinso** [comment]
Glad you found the solution, we do not use "Yarn" and I know nothing about it.
