### ISSUE TITLE
Throw new ERR_HTTP_HEADERS_SENT('set')

### ISSUE THREAD

**Issue by lacoak21** [igvteam/igv-webapp#242]
Hello, when ran npx http-server -p 8787 ./dist and went to the correct address on a browser, I received the error shown below. I am sorry if this was posted before but I could not find any issues in the past dealing with this. 

System:
Ubuntu 20.04.3 LTS
npm@6.14.4
node v10.19.0

[Mon May 09 2022 19:29:20 GMT+0000 (Coordinated Universal Time)]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at module.exports.ResponseStream.(anonymous function) [as setHeader] (/igv-webapp/node_modules/union/lib/response-stream.js:100:34)
    at Object.exports.(anonymous function) (/igv-webapp/node_modules/http-server/lib/core/status-handlers.js:57:7)
    at Readable.stream.on (/igv-webapp/node_modules/http-server/lib/core/index.js:339:22)
    at Readable.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lacoak21** [comment]
Hello I reinstalled npm and nodejs and it worked!

**Comment by helgathorv** [comment]
Great. Thanks for letting us know.

**Comment by dixonmd** [comment]
By updating the node version from v10.19.0 to v16.17.1 worked for me.

```
> curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
> sudo apt install -y nodejs
```
